### ISSUE TITLE
Does not work on Android 14

### ISSUE THREAD

**Issue by ppebb** [AsyJAIZ/Notification-Shade-Transparency#10]
After updating to Android 14, the module now crashes in Lsposed with the following log output:

```
----part 1 start----
[ 2024-02-20T21:14:41.279 1000: 1407: 1407 I/LSPosed-Bridge ] Loading legacy module inc.whew.android.fakegapps from /data/app/~~EVOlFyy24M9DKXkWUB39ow==/inc.whew.android.fakegapps-2lULECTi7zWTEwxv8jOFSg==/base.apk
[ 2024-02-20T21:14:41.283 1000: 1407: 1407 I/LSPosed-Bridge ] Loading class inc.whew.android.fakegapps.FakeSignatures
[ 2024-02-20T21:14:46.490 10160: 2518: 2518 I/LSPosed-Bridge ] Loading legacy module com.asyjaiz.A12blur from /data/app/~~mTPqX822X7PPQUtgsO-Lsg==/com.asyjaiz.A12blur-X5Czn1EWU7eqNty8t3eMqg==/base.apk
[ 2024-02-20T21:14:46.492 10160: 2518: 2518 I/LSPosed-Bridge ] Loading class com.asyjaiz.A12blur.Replace
[ 2024-02-20T21:14:46.548 10160: 2518: 2518 E/LSPosed-Bridge ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.ScrimController(com.android.systemui.statusbar.phone.LightBarController,com.android.systemui.statusbar.phone.DozeParameters,android.app.AlarmManager,com.android.systemui.statusbar.policy.KeyguardStateController,com.android.systemui.util.wakelock.DelayedWakeLock$Builder,android.os.Handler,com.android.keyguard.KeyguardUpdateMonitor,com.android.systemui.dock.DockManager,com.android.systemui.statusbar.policy.ConfigurationController,java.util.concurrent.Executor,com.android.systemui.statusbar.phone.ScreenOffAnimationController,com.android.systemui.keyguard.KeyguardUnlockAnimationController,com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager)#exact at c.fpFN.QxXefqrsgbnjOWh.XposedHelpers.lambda$findConstructorExact$7(Unknown Source:6)
at c.fpFN.QxXefqrsgbnjOWh.XposedHelpers.i(Unknown Source:0) at c.fpFN.QxXefqrsgbnjOWh.b.get(Unknown Source:10) at java.util.Optional.orElseThrow(Optional.java:404)
at c.fpFN.QxXefqrsgbnjOWh.XposedHelpers.findConstructorExact(SourceFile:1)
at c.fpFN.QxXefqrsgbnjOWh.XposedHelpers.findConstructorExact(SourceFile:2)
at com.asyjaiz.A12blur.Replace.findConstructor(Replace.java:180)
at com.asyjaiz.A12blur.Replace.findConstructor(Replace.java:129)
at com.asyjaiz.A12blur.Replace.findConstructor(Replace.java:184)
at com.asyjaiz.A12blur.Replace.handleLoadPackage(Replace.java:222)
at c.fpFN.QxXefqrsgbnjOWh.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
at c.fpFN.QxXefqrsgbnjOWh.callbacks.XC_LoadPackage.call(Unknown Source:6)
at c.fpFN.QxXefqrsgbnjOWh.callbacks.XCallback.callAll(Unknown Source:26) at g0.a(Unknown Source:281)
at java.lang.reflect.Method.invoke(Native Method) at J.callback(Unknown Source:250)
at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
at android.app.LoadedApk.getClassLoader(LoadedApk.java:1135)
at android.app.LoadedApk.getResources(LoadedApk.java:1383)
at android.app.ContextImpl.createAppContext(ContextImpl.java:3324)
at android.app.ContextImpl.createAppContext(ContextImpl.java:3316)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6938)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by Mygod** [comment]
The constructor was changed recently in this commit: https://cs.android.com/android/_/android/platform/frameworks/base/+/f2337c5f8cb23542d8923378e11913a67e3d5633
